In [60]:
import pandas as pd
import os
os.chdir(r"C:\Users\steph\Downloads\lab1\e_comm_project")

In [61]:
df_customer = pd.read_csv(r"C:\Users\steph\Downloads\lab1\e_comm_project\customers_cleaned_csv.csv")
df_transactions = pd.read_csv(r"C:\Users\steph\Downloads\lab1\e_comm_project\transactions_cleaned_csv.csv")

Merging datasets

In [62]:
merged_df = df_transactions.merge(df_customer, on='customer_id', how='left')

In [63]:
merged_df.head(10)

,transaction_id,customer_id,transaction_date,product_id,quantity,unit_price,payment_method,discount_applied,transaction_status,review_text,name,age,gender,state,signup_date,email,phone_number,subscribe
0,TX_0000003568,CUST0429,12/29/2024,WZ-802,30,448000,Credit Card,6.0,Completed,NaN,Hendri,NaN,Male,DI Yogyakarta,8/15/2024,margana84@example.net,8303439050,Yes
1,TX_0000001323,CUST0165,9/20/2025,LE-969,31,326000,E-wallet,7.0,Completed,NaN,Pangeran,58.0,Male,Kepulauan Bangka Belitung,9/20/2025,ranggamaulana@example.net,8556607041,Yes
2,TX_0000007976,CUST0969,9/19/2025,CR-562,22,326000,E-wallet,8.0,Completed,NaN,Sabrina,21.0,Female,Maluku,9/19/2025,mustikaprasasta@example.com,8779287014,Yes
3,TX_0000002408,CUST0293,4/23/2025,BL-316,38,418000,Credit Card,42.0,Completed,NaN,Abyasa,50.0,Male,Aceh,4/12/2025,wibisonocaraka@example.com,8436160362,Yes
4,TX_0000004435,CUST0537,8/28/2025,KL-203,3,15000,E-wallet,27.0,Completed,NaN,Wardaya,58.0,Male,Kalimantan Timur,2/15/2024,wardaya_49@example.com,828349372342,No
5,TX_0000005447,CUST0661,9/22/2025,QQ-301,19,321000,Cash,4.0,Completed,NaN,Puji,32.0,Female,DI Yogyakarta,9/5/2025,puji_62@example.com,82263520270,Yes
6,TX_0000003024,CUST0370,2/10/2025,GW-908,21,473000,Bank Transfer,40.0,Completed,NaN,Kiandra,55.0,Female,NaN,2/7/2025,572kiandra@example.com,8772086268,No
7,TX_0000001534,CUST0193,6/19/2025,GF-891,7,329000,Credit Card,12.0,Completed,Very slow shipping,Kasiyah,45.0,Female,Sulawesi Barat,4/28/2025,537kasiyah@example.com,8096683515,No
8,TX_0000000264,CUST0033,1/16/2025,ON-125,40,105000,Debit Card,40.0,Completed,NaN,Raden,47.0,Male,Kalimantan Selatan,11/16/2023,raden_6@example.com,8448856016,Yes
9,TX_0000000744,CUST0093,10/27/2024,EC-962,30,161000,Debit Card,16.0,Completed,NaN,Syahrini,34.0,Female,NaN,7/14/2024,hariputra@example.com,87412241378,Yes

In [64]:
merged_df.shape

(8199, 18)

In [65]:
print("Customer id total: ",merged_df["customer_id"].count())

Customer id total:  8199

Total revenue

In [66]:
merged_df["revenue"] = merged_df["quantity"] * merged_df["unit_price"]

In [67]:
merged_df.head(10)

,transaction_id,customer_id,transaction_date,product_id,quantity,unit_price,payment_method,discount_applied,transaction_status,review_text,name,age,gender,state,signup_date,email,phone_number,subscribe,revenue
0,TX_0000003568,CUST0429,12/29/2024,WZ-802,30,448000,Credit Card,6.0,Completed,NaN,Hendri,NaN,Male,DI Yogyakarta,8/15/2024,margana84@example.net,8303439050,Yes,13440000
1,TX_0000001323,CUST0165,9/20/2025,LE-969,31,326000,E-wallet,7.0,Completed,NaN,Pangeran,58.0,Male,Kepulauan Bangka Belitung,9/20/2025,ranggamaulana@example.net,8556607041,Yes,10106000
2,TX_0000007976,CUST0969,9/19/2025,CR-562,22,326000,E-wallet,8.0,Completed,NaN,Sabrina,21.0,Female,Maluku,9/19/2025,mustikaprasasta@example.com,8779287014,Yes,7172000
3,TX_0000002408,CUST0293,4/23/2025,BL-316,38,418000,Credit Card,42.0,Completed,NaN,Abyasa,50.0,Male,Aceh,4/12/2025,wibisonocaraka@example.com,8436160362,Yes,15884000
4,TX_0000004435,CUST0537,8/28/2025,KL-203,3,15000,E-wallet,27.0,Completed,NaN,Wardaya,58.0,Male,Kalimantan Timur,2/15/2024,wardaya_49@example.com,828349372342,No,45000
5,TX_0000005447,CUST0661,9/22/2025,QQ-301,19,321000,Cash,4.0,Completed,NaN,Puji,32.0,Female,DI Yogyakarta,9/5/2025,puji_62@example.com,82263520270,Yes,6099000
6,TX_0000003024,CUST0370,2/10/2025,GW-908,21,473000,Bank Transfer,40.0,Completed,NaN,Kiandra,55.0,Female,NaN,2/7/2025,572kiandra@example.com,8772086268,No,9933000
7,TX_0000001534,CUST0193,6/19/2025,GF-891,7,329000,Credit Card,12.0,Completed,Very slow shipping,Kasiyah,45.0,Female,Sulawesi Barat,4/28/2025,537kasiyah@example.com,8096683515,No,2303000
8,TX_0000000264,CUST0033,1/16/2025,ON-125,40,105000,Debit Card,40.0,Completed,NaN,Raden,47.0,Male,Kalimantan Selatan,11/16/2023,raden_6@example.com,8448856016,Yes,4200000
9,TX_0000000744,CUST0093,10/27/2024,EC-962,30,161000,Debit Card,16.0,Completed,NaN,Syahrini,34.0,Female,NaN,7/14/2024,hariputra@example.com,87412241378,Yes,4830000

Amount of customers (unique and non)

In [84]:
print("customers",merged_df["customer_id"].count())

customers 8199

In [74]:
print("unique customers: ", merged_df["customer_id"].nunique())

unique customers:  1000

Age statistical observations and revenue

In [76]:
merged_df["age"].describe(include="all")

count    7715.000000
mean       41.155412
std        13.708438
min        18.000000
25%        29.000000
50%        41.000000
75%        53.000000
max        65.000000
Name: age, dtype: float64

In [82]:
merged_df["revenue"].describe()

count    8.199000e+03
mean     6.804829e+06
std      5.925992e+06
min      7.000000e+02
25%      3.050500e+06
50%      5.796000e+06
75%      9.240000e+06
max      7.593300e+07
Name: revenue, dtype: float64

Balance check

In [77]:
print(merged_df["age"].mean())
print(merged_df["age"].median())

41.155411535968895
41.0

In [79]:
print(merged_df["age"].skew())

-0.0044658691115456745

In [ ]:
# merged_df.to_csv("merged_dataset.csv", index=False)